name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: |
            client/package-lock.json
            server/package-lock.json

      - name: Install Client Dependencies
        working-directory: ./client
        run: npm ci

      - name: Install Server Dependencies
        working-directory: ./server
        run: npm ci

      - name: Run Validations
        run: npm run check

      - name: Enforce pristine working directory
        run: git diff --exit-code || { echo "Working directory is not clean. Lockfile or generated files might be out of sync."; false; }
